const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.Sin,
		C3.Behaviors.solid,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Behaviors.Anchor,
		C3.Plugins.Tilemap,
		C3.Plugins.NinePatch,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.scrollto.Acts.SetEnabled,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.CompareSpeed,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Text.Acts.SubInstanceVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Text.Acts.AddInstanceVar,
		C3.Plugins.Touch.Cnds.OnHoldGestureObject,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Acts.SubVar
	];
};
self.C3_JsPropNameTable = [
	{Платформер: 0},
	{СледитьЗа: 0},
	{BoundToLayout: 0},
	{Character: 0},
	{Sprite: 0},
	{game_title: 0},
	{Sine: 0},
	{Solid: 0},
	{platform: 0},
	{cp_id: 0},
	{checkpoint: 0},
	{version_counter: 0},
	{text_state: 0},
	{btn_menu_text: 0},
	{lvl_btn_number: 0},
	{txt_lvl_win_tittle: 0},
	{star_on_level: 0},
	{Твёрдый: 0},
	{ТайловыйФон: 0},
	{ТайловыйФон3: 0},
	{ТайловыйФон4: 0},
	{ТайловыйФон5: 0},
	{Anchor: 0},
	{btn_jump: 0},
	{btn_left: 0},
	{btn_right: 0},
	{area_jump: 0},
	{area_left: 0},
	{area_right: 0},
	{icon_star: 0},
	{settings: 0},
	{heart_icon: 0},
	{count_lives: 0},
	{score_lifes: 0},
	{scrore_count: 0},
	{count_layer: 0},
	{Sprite8: 0},
	{Tilemap: 0},
	{menu_back: 0},
	{button_bottom_layer: 0},
	{btn_menu_play: 0},
	{btn_menu_map: 0},
	{btn_menu_shop: 0},
	{btn_menu_settings: 0},
	{map_back: 0},
	{Sprite2: 0},
	{btn_map_back: 0},
	{lvl_bottom_layer: 0},
	{lvl_window_title: 0},
	{enemy_count: 0},
	{enemy: 0},
	{btn_map_left: 0},
	{btn_map_right: 0},
	{lvl_btn_state: 0},
	{lvl_button: 0},
	{Клавиатура: 0},
	{Touch: 0},
	{Audio: 0},
	{score: 0},
	{current_checkpoint: 0},
	{enemy_type: 0},
	{map_gorizont: 0},
	{map_vertical: 0},
	{levels_complete: 0}
];

self.InstanceType = {
	Character: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	game_title: class extends self.ISpriteInstance {},
	platform: class extends self.ISpriteInstance {},
	checkpoint: class extends self.ISpriteInstance {},
	version_counter: class extends self.ITextInstance {},
	btn_menu_text: class extends self.ITextInstance {},
	lvl_btn_number: class extends self.ITextInstance {},
	txt_lvl_win_tittle: class extends self.ITextInstance {},
	star_on_level: class extends self.ISpriteInstance {},
	ТайловыйФон: class extends self.ITiledBackgroundInstance {},
	ТайловыйФон3: class extends self.ITiledBackgroundInstance {},
	ТайловыйФон4: class extends self.ITiledBackgroundInstance {},
	ТайловыйФон5: class extends self.ITiledBackgroundInstance {},
	btn_jump: class extends self.ISpriteInstance {},
	btn_left: class extends self.ISpriteInstance {},
	btn_right: class extends self.ISpriteInstance {},
	area_jump: class extends self.ISpriteInstance {},
	area_left: class extends self.ISpriteInstance {},
	area_right: class extends self.ISpriteInstance {},
	icon_star: class extends self.ISpriteInstance {},
	settings: class extends self.ISpriteInstance {},
	heart_icon: class extends self.ISpriteInstance {},
	score_lifes: class extends self.ITextInstance {},
	scrore_count: class extends self.ITextInstance {},
	count_layer: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	menu_back: class extends self.ISpriteInstance {},
	button_bottom_layer: class extends self.ISpriteInstance {},
	btn_menu_play: class extends self.ISpriteInstance {},
	btn_menu_map: class extends self.ISpriteInstance {},
	btn_menu_shop: class extends self.ISpriteInstance {},
	btn_menu_settings: class extends self.ISpriteInstance {},
	map_back: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	btn_map_back: class extends self.ISpriteInstance {},
	lvl_bottom_layer: class extends self.I9PatchInstance {},
	lvl_window_title: class extends self.ISpriteInstance {},
	enemy: class extends self.ISpriteInstance {},
	btn_map_left: class extends self.ISpriteInstance {},
	btn_map_right: class extends self.ISpriteInstance {},
	lvl_button: class extends self.ISpriteInstance {},
	Клавиатура: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {}
}