const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.Sin,
		C3.Behaviors.solid,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.scrollto.Acts.SetEnabled,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.CompareSpeed,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Text.Acts.SubInstanceVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.TiledBg.Acts.MoveToTop,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.SetAnimFrame
	];
};
self.C3_JsPropNameTable = [
	{Платформер: 0},
	{СледитьЗа: 0},
	{BoundToLayout: 0},
	{Спрайт2: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{btn_play: 0},
	{btn_settings: 0},
	{btn_shop: 0},
	{game_title: 0},
	{Sine: 0},
	{Solid: 0},
	{platform: 0},
	{count_layer: 0},
	{scrore_count: 0},
	{ver: 0},
	{Text: 0},
	{count_lives: 0},
	{score_lifes: 0},
	{Твёрдый: 0},
	{ТайловыйФон: 0},
	{ТайловыйФон2: 0},
	{ТайловыйФон3: 0},
	{ТайловыйФон4: 0},
	{Клавиатура: 0},
	{star_on_level: 0},
	{Touch: 0},
	{btn_right: 0},
	{btn_left: 0},
	{btn_jump: 0},
	{ТайловыйФон5: 0},
	{Sprite4: 0},
	{Audio: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{settings: 0},
	{icon_star: 0},
	{Sprite3: 0},
	{score: 0}
];

self.InstanceType = {
	Спрайт2: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	btn_play: class extends self.ISpriteInstance {},
	btn_settings: class extends self.ISpriteInstance {},
	btn_shop: class extends self.ISpriteInstance {},
	game_title: class extends self.ISpriteInstance {},
	platform: class extends self.ISpriteInstance {},
	count_layer: class extends self.ISpriteInstance {},
	scrore_count: class extends self.ITextInstance {},
	ver: class extends self.ITextInstance {},
	Text: class extends self.ITextInstance {},
	score_lifes: class extends self.ITextInstance {},
	ТайловыйФон: class extends self.ITiledBackgroundInstance {},
	ТайловыйФон2: class extends self.ITiledBackgroundInstance {},
	ТайловыйФон3: class extends self.ITiledBackgroundInstance {},
	ТайловыйФон4: class extends self.ITiledBackgroundInstance {},
	Клавиатура: class extends self.IInstance {},
	star_on_level: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	btn_right: class extends self.ISpriteInstance {},
	btn_left: class extends self.ISpriteInstance {},
	btn_jump: class extends self.ISpriteInstance {},
	ТайловыйФон5: class extends self.ITiledBackgroundInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	settings: class extends self.ISpriteInstance {},
	icon_star: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {}
}